name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get install -y libxkbcommon-dev libwayland-dev
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: linea-linux
          path: target/release/Linea

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: linea-windows
          path: target/release/Linea.exe